/** Target language + listing currency per marketplace (26 approved platforms). */
export const marketplaceLocale: Record<string, { lang: string; currency: string }> = {
  aliexpress: { lang: "zh", currency: "CNY" },
  allegro: { lang: "pl", currency: "PLN" },
  amazon: { lang: "en", currency: "USD" },
  bigcommerce: { lang: "en", currency: "USD" },
  bolcom: { lang: "nl", currency: "EUR" },
  depop: { lang: "en", currency: "USD" },
  ebay: { lang: "en", currency: "USD" },
  etsy: { lang: "en", currency: "USD" },
  flipkart: { lang: "en", currency: "INR" },
  fruugo: { lang: "en", currency: "GBP" },
  lazada: { lang: "en", currency: "SGD" },
  magento: { lang: "en", currency: "USD" },
  mercadolibre: { lang: "es", currency: "ARS" },
  mercadolibre_br: { lang: "pt", currency: "BRL" },
  newegg: { lang: "en", currency: "USD" },
  poshmark: { lang: "en", currency: "USD" },
  rakuten: { lang: "ja", currency: "JPY" },
  shopee: { lang: "en", currency: "SGD" },
  shopify: { lang: "en", currency: "USD" },
  stockx: { lang: "en", currency: "USD" },
  taobao: { lang: "zh", currency: "CNY" },
  tiktokshop: { lang: "en", currency: "USD" },
  vinted: { lang: "en", currency: "EUR" },
  wayfair: { lang: "en", currency: "USD" },
  woocommerce: { lang: "en", currency: "USD" },
  zalando: { lang: "de", currency: "EUR" },
};

export const currencyRates: Record<string, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 149.5,
  BRL: 5.1,
  ARS: 900,
  CNY: 7.2,
  INR: 83,
  SGD: 1.35,
  PLN: 4.01,
};
