/**
 * OAuth provider manifest for all 26 Kauf26 marketplaces.
 * Redirect URIs follow kauf26://oauth/{id} — register each in the marketplace developer portal.
 */
import { getOAuthRedirectUri } from "./oauthRedirect";
import type { MarketplaceOAuthManifestEntry } from "./marketplaceOAuthTypes";

function entry(
  partial: Omit<
    MarketplaceOAuthManifestEntry,
    "redirectUriRegistrationHint"
  > & { id: string }
): MarketplaceOAuthManifestEntry {
  const redirect = getOAuthRedirectUri(partial.id);
  return {
    ...partial,
    redirectUriRegistrationHint: `Register exact redirect URI: ${redirect}`,
  };
}

export const MARKETPLACE_OAUTH_MANIFEST: MarketplaceOAuthManifestEntry[] = [
  entry({
    id: "aliexpress",
    name: "AliExpress",
    authUrl: "https://oauth.aliexpress.com/authorize",
    tokenUrl: "https://oauth.aliexpress.com/token",
    userInfoUrl: "https://api-sg.aliexpress.com/sync?method=aliexpress.solution.merchant.profile.get",
    clientIdEnv: "ALIEXPRESS_APP_KEY",
    mobileClientSecretEnv: "EXPO_PUBLIC_ALIEXPRESS_APP_SECRET",
    scopes: ["read", "write"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { accountLabel: ["seller_name"], email: ["email"] },
    developerPortalUrl: "https://openservice.aliexpress.com",
  }),
  entry({
    id: "allegro",
    name: "Allegro",
    authUrl: "https://allegro.pl/auth/oauth/authorize",
    tokenUrl: "https://allegro.pl/auth/oauth/token",
    userInfoUrl: "https://api.allegro.pl/me",
    clientIdEnv: "ALLEGRO_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_ALLEGRO_CLIENT_SECRET",
    scopes: ["allegro:api:sale:offers:write", "allegro:api:profile:read"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: {
      name: ["firstName", "lastName"],
      email: ["email"],
      userId: ["id"],
    },
    developerPortalUrl: "https://developer.allegro.pl",
  }),
  entry({
    id: "amazon",
    name: "Amazon",
    authUrl: "https://sellercentral.amazon.com/apps/authorize/consent",
    tokenUrl: "https://api.amazon.com/auth/o2/token",
    userInfoUrl: "https://api.amazon.com/user/profile",
    clientIdEnv: "AMAZON_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_AMAZON_CLIENT_SECRET",
    scopes: ["sellingpartnerapi::notifications", "sellingpartnerapi::listings"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["name"], email: ["email"], userId: ["user_id"] },
    developerPortalUrl: "https://sellercentral.amazon.com/sellingpartner/developerconsole",
    notes: "Login with Amazon / SP-API consent flow.",
  }),
  entry({
    id: "bigcommerce",
    name: "BigCommerce",
    authUrl: "https://login.bigcommerce.com/oauth2/authorize",
    tokenUrl: "https://login.bigcommerce.com/oauth2/token",
    userInfoUrl: "https://api.bigcommerce.com/stores/{store_hash}/v2/store",
    clientIdEnv: "BIGCOMMERCE_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_BIGCOMMERCE_CLIENT_SECRET",
    scopes: ["store_v2_products"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["administrator_first_name"], email: ["administrator_email"] },
    urlPlaceholders: ["base"],
    developerPortalUrl: "https://developer.bigcommerce.com",
  }),
  entry({
    id: "bolcom",
    name: "Bol.com",
    authUrl: "https://login.bol.com/token/authorize",
    tokenUrl: "https://login.bol.com/token",
    userInfoUrl: "https://api.bol.com/retailer/retailers/current",
    clientIdEnv: "BOLCOM_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_BOLCOM_CLIENT_SECRET",
    scopes: ["RETAILER"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { accountLabel: ["displayName"], email: ["email"] },
    developerPortalUrl: "https://developer.bol.com",
  }),
  entry({
    id: "depop",
    name: "Depop",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "DEPOP_API_KEY",
    scopes: [],
    oauthFlow: "partnership",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://depop.com/partners",
    notes: "Partnership API — no public OAuth for third-party mobile apps.",
  }),
  entry({
    id: "ebay",
    name: "eBay",
    authUrl: "https://auth.ebay.com/oauth2/authorize",
    tokenUrl: "https://api.ebay.com/identity/v1/oauth2/token",
    userInfoUrl: "https://apiz.ebay.com/commerce/identity/v1/user/",
    clientIdEnv: "EBAY_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_EBAY_CLIENT_SECRET",
    scopes: [
      "https://api.ebay.com/oauth/api_scope/sell.inventory",
      "https://api.ebay.com/oauth/api_scope/sell.account",
      "https://api.ebay.com/oauth/api_scope/commerce.identity.readonly",
    ],
    oauthFlow: "authorization_code_basic",
    oauthSupported: true,
    tokenExchange: "form_basic",
    userInfoAuth: "ebay",
    userInfoMapping: {
      name: ["individualAccount.firstName", "individualAccount.lastName"],
      email: ["individualAccount.email"],
      accountLabel: ["username"],
    },
    developerPortalUrl: "https://developer.ebay.com/my/keys",
    notes:
      "Android: Chrome Custom Tabs (same as eBay OAuth library redirect handling). iOS: ASWebAuthenticationSession.",
  }),
  entry({
    id: "etsy",
    name: "Etsy",
    authUrl: "https://www.etsy.com/oauth/connect",
    tokenUrl: "https://api.etsy.com/v3/public/oauth/token",
    userInfoUrl: "https://api.etsy.com/v3/application/users/me",
    clientIdEnv: "ETSY_CLIENT_ID",
    scopes: ["email_r", "listings_r", "listings_w", "shops_r", "shops_w"],
    oauthFlow: "authorization_code_pkce",
    oauthSupported: true,
    tokenExchange: "json_pkce",
    userInfoAuth: "etsy",
    usePkce: true,
    userInfoMapping: {
      name: ["first_name", "last_name"],
      email: ["primary_email"],
      userId: ["user_id"],
    },
    developerPortalUrl: "https://www.etsy.com/developers/your-apps",
    notes: "Access token ~1 hour; refresh token ~90 days.",
  }),
  entry({
    id: "flipkart",
    name: "Flipkart",
    authUrl: "https://api.flipkart.net/oauth-service/oauth/authorize",
    tokenUrl: "https://api.flipkart.net/oauth-service/oauth/token",
    userInfoUrl: "https://api.flipkart.net/sellers/profile",
    clientIdEnv: "FLIPKART_APP_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_FLIPKART_APP_SECRET",
    scopes: ["Seller_Api"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["sellerName"], email: ["email"] },
    developerPortalUrl: "https://seller.flipkart.com",
  }),
  entry({
    id: "fruugo",
    name: "Fruugo",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "FRUUGO_API_KEY",
    scopes: [],
    oauthFlow: "api_key",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://www.fruugo.com/partners",
    notes: "Merchant API key — no seller OAuth redirect flow.",
  }),
  entry({
    id: "lazada",
    name: "Lazada",
    authUrl: "https://auth.lazada.com/oauth/authorize",
    tokenUrl: "https://auth.lazada.com/rest/restapis/oauth/token",
    userInfoUrl: "https://api.lazada.com/rest/seller/get",
    clientIdEnv: "LAZADA_APP_KEY",
    mobileClientSecretEnv: "EXPO_PUBLIC_LAZADA_APP_SECRET",
    scopes: ["read_products", "write_products"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["name"], email: ["email"] },
    developerPortalUrl: "https://open.lazada.com",
  }),
  entry({
    id: "magento",
    name: "Magento (Adobe Commerce)",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "MAGENTO_ACCESS_TOKEN",
    scopes: [],
    oauthFlow: "api_key",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    requiresBaseUrl: true,
    developerPortalUrl: "https://developer.adobe.com/commerce",
    notes: "Use admin integration / access token — not mobile OAuth.",
  }),
  entry({
    id: "mercadolibre",
    name: "MercadoLibre",
    authUrl: "https://auth.mercadolibre.com/authorization",
    tokenUrl: "https://api.mercadolibre.com/oauth/token",
    userInfoUrl: "https://api.mercadolibre.com/users/me",
    clientIdEnv: "MERCADOLIBRE_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_MERCADOLIBRE_CLIENT_SECRET",
    scopes: ["read", "write", "offline_access"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: {
      name: ["first_name", "last_name"],
      email: ["email"],
      userId: ["id"],
      accountLabel: ["nickname"],
    },
    developerPortalUrl: "https://developers.mercadolibre.com",
  }),
  entry({
    id: "mercadolibre_br",
    name: "Mercado Livre (Brazil)",
    authUrl: "https://auth.mercadolibre.com.br/authorization",
    tokenUrl: "https://api.mercadolibre.com/oauth/token",
    userInfoUrl: "https://api.mercadolibre.com/users/me",
    clientIdEnv: "MERCADOLIBRE_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_MERCADOLIBRE_CLIENT_SECRET",
    scopes: ["read", "write", "offline_access"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: {
      name: ["first_name", "last_name"],
      email: ["email"],
      userId: ["id"],
    },
    developerPortalUrl: "https://developers.mercadolivre.com.br",
    notes: "Uses MLB site — separate redirect URI from global MercadoLibre.",
  }),
  entry({
    id: "newegg",
    name: "Newegg",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "NEWEGG_API_KEY",
    scopes: [],
    oauthFlow: "api_key",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://developer.newegg.com",
    notes: "Seller API key — no OAuth redirect.",
  }),
  entry({
    id: "poshmark",
    name: "Poshmark",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "POSHMARK_PARTNERSHIP_KEY",
    scopes: [],
    oauthFlow: "partnership",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://poshmark.com/partners",
    notes: "Partnership-only integration.",
  }),
  entry({
    id: "rakuten",
    name: "Rakuten",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "RAKUTEN_SERVICE_SECRET",
    scopes: [],
    oauthFlow: "api_key",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://webservice.rakuten.co.jp",
    notes: "RMS service secret / license key — no mobile OAuth.",
  }),
  entry({
    id: "shopee",
    name: "Shopee",
    authUrl: "https://partner.shopeemobile.com/api/v2/shop/auth_partner",
    tokenUrl: "https://partner.shopeemobile.com/api/v2/auth/token/get",
    userInfoUrl: "https://partner.shopeemobile.com/api/v2/shop/get_shop_info",
    clientIdEnv: "SHOPEE_PARTNER_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_SHOPEE_PARTNER_KEY",
    scopes: ["shop"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { accountLabel: ["shop_name"], email: ["email"] },
    developerPortalUrl: "https://open.shopee.com",
  }),
  entry({
    id: "shopify",
    name: "Shopify",
    authUrl: "https://{shop}/admin/oauth/authorize",
    tokenUrl: "https://{shop}/admin/oauth/access_token",
    userInfoUrl: "https://{shop}/admin/api/2024-10/shop.json",
    clientIdEnv: "SHOPIFY_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_SHOPIFY_CLIENT_SECRET",
    scopes: ["read_products", "write_products"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "json_secret",
    userInfoAuth: "shopify",
    requiresShopDomain: true,
    urlPlaceholders: ["shop"],
    userInfoMapping: {
      name: ["shop.shop_owner"],
      email: ["shop.email"],
      accountLabel: ["shop.name"],
    },
    developerPortalUrl: "https://partners.shopify.com",
    notes:
      "Optional: configure MobilePlatformApplication + universal links for shared web credentials on iOS.",
  }),
  entry({
    id: "stockx",
    name: "StockX",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "STOCKX_API_KEY",
    scopes: [],
    oauthFlow: "partnership",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://stockx.com/partners",
    notes: "Partnership API only.",
  }),
  entry({
    id: "taobao",
    name: "Taobao",
    authUrl: "https://oauth.taobao.com/authorize",
    tokenUrl: "https://oauth.taobao.com/token",
    userInfoUrl: "https://eco.taobao.com/router/rest",
    clientIdEnv: "TAOBAO_APP_KEY",
    mobileClientSecretEnv: "EXPO_PUBLIC_TAOBAO_APP_SECRET",
    scopes: ["item"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    developerPortalUrl: "https://open.taobao.com",
    notes: "Taobao Open Platform — seller authorization required.",
  }),
  entry({
    id: "tiktokshop",
    name: "TikTok Shop",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "TIKTOKSHOP_APP_KEY",
    scopes: [],
    oauthFlow: "partnership",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://partner.tiktokshop.com",
    notes: "TikTok Shop partner program — apply for OAuth access.",
  }),
  entry({
    id: "vinted",
    name: "Vinted",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "VINTED_API_KEY",
    scopes: [],
    oauthFlow: "partnership",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    developerPortalUrl: "https://www.vinted.com/partners",
    notes: "No public seller OAuth API.",
  }),
  entry({
    id: "wayfair",
    name: "Wayfair",
    authUrl: "https://sso.auth.wayfair.com/oauth/authorize",
    tokenUrl: "https://sso.auth.wayfair.com/oauth/token",
    userInfoUrl: "https://api.wayfair.com/v1/supplier/profile",
    clientIdEnv: "WAYFAIR_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_WAYFAIR_CLIENT_SECRET",
    scopes: ["supplier:write"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["contactName"], email: ["email"] },
    developerPortalUrl: "https://developer.wayfair.com",
  }),
  entry({
    id: "woocommerce",
    name: "WooCommerce",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    clientIdEnv: "WOOCOMMERCE_CONSUMER_KEY",
    scopes: [],
    oauthFlow: "api_key",
    oauthSupported: false,
    tokenExchange: "form_secret",
    userInfoAuth: "none",
    requiresSiteUrl: true,
    developerPortalUrl: "https://woocommerce.com/document/woocommerce-rest-api",
    notes: "REST API keys from wp-admin — WooCommerce OAuth 1.0a is not used for mobile one-tap.",
  }),
  entry({
    id: "zalando",
    name: "Zalando",
    authUrl: "https://api.zalando.com/auth/authorize",
    tokenUrl: "https://api.zalando.com/auth/token",
    userInfoUrl: "https://api.zalando.com/merchants/me",
    clientIdEnv: "ZALANDO_CLIENT_ID",
    mobileClientSecretEnv: "EXPO_PUBLIC_ZALANDO_CLIENT_SECRET",
    scopes: ["access_token"],
    oauthFlow: "authorization_code_secret",
    oauthSupported: true,
    tokenExchange: "form_secret",
    userInfoAuth: "bearer",
    userInfoMapping: { name: ["name"], email: ["email"] },
    developerPortalUrl: "https://partner.zalando.com",
  }),
];

export const MARKETPLACE_OAUTH_MANIFEST_BY_ID = new Map(
  MARKETPLACE_OAUTH_MANIFEST.map((m) => [m.id, m])
);

export function getOAuthManifestEntry(id: string): MarketplaceOAuthManifestEntry | undefined {
  return MARKETPLACE_OAUTH_MANIFEST_BY_ID.get(id.toLowerCase());
}

export function getOAuthSupportedManifestEntries(): MarketplaceOAuthManifestEntry[] {
  return MARKETPLACE_OAUTH_MANIFEST.filter((m) => m.oauthSupported);
}

export const MARKETPLACE_OAUTH_MANIFEST_COUNT = MARKETPLACE_OAUTH_MANIFEST.length;
